/*
 * generated by Xtext 2.34.0
 */
package com.hcjds.dsl.parser.antlr;

import com.google.inject.Inject;
import com.hcjds.dsl.parser.antlr.internal.InternalCeyParser;
import com.hcjds.dsl.services.CeyGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CeyParser extends AbstractAntlrParser {

	@Inject
	private CeyGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCeyParser createParser(XtextTokenStream stream) {
		return new InternalCeyParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public CeyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CeyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
