/*
 * generated by Xtext 2.34.0
 */
package com.hcjds.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CeyRuntimeModule extends AbstractCeyRuntimeModule {
}
