/*
 * generated by Xtext 2.34.0
 */
package com.hcjds.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CeyStandaloneSetup extends CeyStandaloneSetupGenerated {

	public static void doSetup() {
		new CeyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
