/*
 * generated by Xtext 2.34.0
 */
package com.hcjds.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.hcjds.dsl.CeyRuntimeModule;
import com.hcjds.dsl.CeyStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CeyIdeSetup extends CeyStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CeyRuntimeModule(), new CeyIdeModule()));
	}
	
}
