/*
 * generated by Xtext 2.34.0
 */
package com.hcjds.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCeyScopeProvider extends DelegatingScopeProvider {
}
